# Generated by Django 5.1 on 2024-09-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('CANDIDATO', 'Candidato'), ('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo')], default='CANDIDATO', max_length=10),
        ),
    ]
